services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Noviigod1!
      POSTGRES_DB: blog_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - blog-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=postgresql://postgres:Noviigod1!@db:5432/blog_db
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=Dora
      - MINIO_SECRET_KEY=Noviigod1!
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USER=dasasiraeva882@gmail.com
      - SMTP_PASSWORD=fmhnkstlczbromxe
      - TZ=Europe/Moscow
    volumes:
      - .:/app
    command: uvicorn src.main:app --host 0.0.0.0 --port 8001 --reload --log-level debug
    networks:
      - blog-network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - blog-network

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=Dora
      - MINIO_ROOT_PASSWORD=Noviigod1!
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - blog-network

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A src.celery_app worker --loglevel=info --pool=solo
    depends_on:
      - rabbitmq
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:Noviigod1!@db:5432/blog_db
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=Dora
      - MINIO_SECRET_KEY=Noviigod1!
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USER=dasasiraeva882@gmail.com
      - SMTP_PASSWORD=fmhnkstlczbromxe
    volumes:
      - .:/app
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - blog-network

volumes:
  postgres_data:
  minio_data:

networks:
  blog-network:
    driver: bridge