"""Update deleted_articles with all fields

Revision ID: 1db0888f6dc5
Revises: 69719bbc669f
Create Date: 2025-04-09 22:32:37.280684

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1db0888f6dc5'
down_revision: Union[str, None] = '69719bbc669f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_articles_title_content', table_name='articles', postgresql_using='gin')
    op.create_index('ix_articles_title_content', 'articles', [sa.literal_column("to_tsvector('russian', title || ' ' || content)")], unique=False, postgresql_using='gin')
    op.add_column('deleted_articles', sa.Column('title', sa.String(), nullable=False))
    op.add_column('deleted_articles', sa.Column('content', sa.String(), nullable=False))
    op.add_column('deleted_articles', sa.Column('category_id', sa.Integer(), nullable=True))
    op.add_column('deleted_articles', sa.Column('image_url', sa.String(), nullable=True))
    op.alter_column('deleted_articles', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_deleted_articles_id', table_name='deleted_articles')
    op.drop_constraint('deleted_articles_article_id_fkey', 'deleted_articles', type_='foreignkey')
    op.create_foreign_key(None, 'deleted_articles', 'categories', ['category_id'], ['id'])
    op.drop_column('deleted_articles', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deleted_articles', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'deleted_articles', type_='foreignkey')
    op.create_foreign_key('deleted_articles_article_id_fkey', 'deleted_articles', 'articles', ['article_id'], ['id'])
    op.create_index('ix_deleted_articles_id', 'deleted_articles', ['id'], unique=False)
    op.alter_column('deleted_articles', 'deleted_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('deleted_articles', 'image_url')
    op.drop_column('deleted_articles', 'category_id')
    op.drop_column('deleted_articles', 'content')
    op.drop_column('deleted_articles', 'title')
    op.drop_index('ix_articles_title_content', table_name='articles', postgresql_using='gin')
    op.create_index('ix_articles_title_content', 'articles', [sa.literal_column("to_tsvector('russian'::regconfig, (title::text || ' '::text) || content::text)")], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###
