"""Sync all tables

Revision ID: 8ae01480f0cb
Revises: 1db0888f6dc5
Create Date: 2025-04-13 07:45:48.922246

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8ae01480f0cb'
down_revision: Union[str, None] = '1db0888f6dc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_articles_title_content', table_name='articles', postgresql_using='gin')
    op.create_index('ix_articles_title_content', 'articles', [sa.literal_column("to_tsvector('russian', title || ' ' || content)")], unique=False, postgresql_using='gin')
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('ix_articles_title_content', table_name='articles', postgresql_using='gin')
    op.create_index('ix_articles_title_content', 'articles', [sa.literal_column("to_tsvector('russian'::regconfig, (title::text || ' '::text) || content::text)")], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###
